services:

  mysql:
    image: mysql:latest
    volumes:
      - user-demo-thymeleaf:/var/lib/mysql
    environment:
      MYSQL_DATABASE: userDB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  user-demo-thymeleaf:
